baseURL = "/"
languageCode = "nb-NO"
title = "Veidemann dashboard documentation"
author = "Nettarkivet"
theme = "hugo-theme-learn"

[params]
  description = "Dokumentasjon for veidemann dashboard "
  themeVariant = "blue"
 #showVisitedLinks = true
 #disableBreadcrumb = true
 #disableNextPrev = true

[outputs]
home = [ "HTML", "RSS", "JSON"]